version: "3.8"

services:
  go:
    container_name: go-sample
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080